[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme iceberg
'''
